version: 2
updates:
  # Monitor npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@vpursuit"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    # Security updates get priority
    allow:
      - dependency-type: "all"
    # Group non-security updates
    groups:
      production-dependencies:
        patterns:
          - "@modelcontextprotocol/*"
          - "zod"
      development-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "typescript"
          - "vitest"
          - "eslint*"
        update-types:
          - "minor"
          - "patch"