blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/vpursuit/swipl-mcp-server/blob/main/README.md
    about: Check the README and documentation first
  - name: 🔧 MCP Inspector
    url: https://github.com/modelcontextprotocol/inspector
    about: Use MCP Inspector to debug MCP protocol issues
  - name: 💬 Discussions
    url: https://github.com/vpursuit/swipl-mcp-server/discussions
    about: Ask questions and discuss ideas with the community