name: Feature Request
description: Suggest a new feature or enhancement for the SWI-Prolog MCP Server
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
projects: ["swipl-mcp-server"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature you'd like...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What's the current limitation?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Alternative approaches could be...

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - Query execution (standard mode)
        - Query execution (engine mode)
        - Database operations (assert/retract)
        - File loading (consult)
        - Symbol/predicate listing
        - Security/sandboxing
        - Performance
        - Documentation
        - Testing
        - CLI/tooling
        - MCP protocol
        - Other

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific use case or scenario where this feature would be helpful.
      placeholder: This would be useful when...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, examples, or screenshots about the feature request.
      placeholder: Add any other context here...